name: Lint
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log Node Version
        run: node -v
      - name: Install Dependencies
        run: npm i
      - name: Run ESLint
        run: npm run lint
